// Reference copy - delete after SearchPage is fixed
export const SEARCH_PAGE_COPY = {
  searchUnavailable: "索引不可用，请先构建或重建索引。",
  queryEyebrow: "查询",
  title: "搜索页面",
  staleIndex: "当前搜索结果可能来自旧索引。",
  searchAria: "搜索输入",
  placeholder: "输入中文或英文关键词",
  searching: "搜索中...",
  search: "搜索",
  rebuilding: "索引重建中...",
  buildIndex: "构建索引",
  rebuildIndex: "重建索引",
  searchFailed: "搜索失败",
  results: "结果列表",
  empty: "空",
  resultCount: (count: number) => `${count} 条`,
  waitWorkspace: "等待工作区",
  waitWorkspaceDesc: "选择工作区后可搜索已索引页面。",
  indexUnavailable: "索引不可用",
  noIndexableHint: "请先在设置中配置模型，并在工作台完成页面分析后再构建索引。",
  indexBuilding: "索引正在构建，请稍候。",
  buildIndexFirst: "请先构建索引。",
  noMatches: "没有匹配结果",
  noMatchesDesc: (q: string) => `未找到与「${q}」相关的页面，请尝试其他关键词。`,
  noResultsYet: "暂无搜索结果",
  noResultsYetDesc: "输入关键词并点击搜索，结果将按相关性排序显示。",
  preview: "图片预览",
  available: "可用",
  missing: "缺失",
  selectOne: "待选择",
  imageMissing: "页面图片不可用，可能已被移动或删除。",
  previewLoading: "正在加载图片预览...",
  selectForPreview: "选择搜索结果后，页面图片预览会显示在这里。",
  jsonView: "JSON 查看",
  selectForJson: "请选择搜索结果",
  checking: "检查中",
  indexReady: "索引可用",
  building: "构建中",
  indexFailed: "索引失败",
  needsRebuild: "需要重建",
  notBuilt: "索引未建立",
  loadingStatus: "加载索引状态中…",
  opFailed: "操作失败",
  unknownDoc: "未知文档",
};
